// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroRecords.DataAccess.DataContext;

#nullable disable

namespace RetroRecords_RecordAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20231016112416_SeedRecordTableWithInitialSeedData")]
    partial class SeedRecordTableWithInitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetroRecords_RecordAPI.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("RunTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "David Bowie",
                            CreatedAt = new DateTime(2023, 10, 16, 12, 24, 16, 359, DateTimeKind.Local).AddTicks(2498),
                            Genre = "Glam Rock",
                            Label = "RCA",
                            Name = "Aladdin Sane",
                            ReleaseDate = new DateTime(1973, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 41, 32, 0)
                        },
                        new
                        {
                            Id = 2,
                            Artist = "David Bowie",
                            CreatedAt = new DateTime(2023, 10, 16, 12, 24, 16, 359, DateTimeKind.Local).AddTicks(2544),
                            Genre = "Rock",
                            Label = "RCA",
                            Name = "Station To Station",
                            ReleaseDate = new DateTime(1976, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 37, 54, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
