// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroRecords.DataAccess.DataContext;

#nullable disable

namespace RetroRecords_RecordAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetroRecords_RecordAPI.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("RunTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "David Bowie",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4662),
                            Genre = "Glam Rock",
                            Label = "RCA",
                            Name = "Aladdin Sane",
                            ReleaseDate = new DateTime(1973, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 41, 32, 0)
                        },
                        new
                        {
                            Id = 2,
                            Artist = "David Bowie",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4711),
                            Genre = "Rock",
                            Label = "RCA",
                            Name = "Station To Station",
                            ReleaseDate = new DateTime(1976, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 37, 54, 0)
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Prince",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4715),
                            Genre = "Funk Pop",
                            Label = "Warner Bros.",
                            Name = "Purple Rain",
                            ReleaseDate = new DateTime(1984, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 43, 55, 0)
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Genesis",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4717),
                            Genre = "Prog Rock",
                            Label = "Charisma",
                            Name = "Selling England By The Pound",
                            ReleaseDate = new DateTime(1973, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 53, 44, 0)
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Supertramp",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4720),
                            Genre = "Pop",
                            Label = "A&M",
                            Name = "Breakfast In America",
                            ReleaseDate = new DateTime(1979, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 46, 6, 0)
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Opeth",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4722),
                            Genre = "Metal",
                            Label = "Candlelight",
                            Name = "My Arms, Your Hearse",
                            ReleaseDate = new DateTime(1998, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 52, 34, 0)
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Kraftwerk",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4725),
                            Genre = "Electronica",
                            Label = "Kling Klang",
                            Name = "Computer World",
                            ReleaseDate = new DateTime(1981, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 34, 25, 0)
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Metallica",
                            CreatedAt = new DateTime(2023, 10, 17, 15, 29, 56, 822, DateTimeKind.Local).AddTicks(4727),
                            Genre = "Metal",
                            Label = "Elektra",
                            Name = "Master of Puppets",
                            ReleaseDate = new DateTime(1986, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RunTime = new TimeSpan(0, 0, 54, 52, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
